
[intervals]
	autoclose = 30

[discord]

	[discord.channels]
		appealChannelID = "579810718963204117"
		loggingChannelID = "579810731684397066"

	[discord.categories]
		appealCategoryID = "579810765742014478"

	[discord.embeds]
		color = 16711680
		footer = "DirtCraft Appeals System | 2019"
		title = ":redbulletpoint: DirtCraft Appeals :redbulletpoint:"

