
[discord]

	[discord.embeds]
		color = 16711680
		footer = "DirtCraft's DirtBot | 2019"
		title = ":redbulletpoint: DirtCraft's DirtBot :redbulletpoint:"

[servers]

	[servers.old]
		maps = [["FTB Infinity Evolved", "https://drive.google.com/drive/folders/1eU6Z9P81ArtAlJ0MCtmLk0kSUFoznXjx", "08/2018-02/2019"], ["FTB Revelation", "https://drive.google.com/file/d/1HdbsrFUOysXn7tshkMEzyZJ5NdUZTl5B/view", "01/2019-05/2019"]]

